name: Boudoir Stories
favicon: null
layout_spectrum: 0.9136961137410253
typography_spectrum: 0.9604611080139875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4b484c'
    - '#b8aaa6'
    - '#796d65'
    - '#e4e4e4'
  brandStrength: 0.5433329921215773
  lightness: 0.3487150811124593
  saturation: 0.11300532799214125
  rhythmicContrast: 0.7878612407948822
purpose: []
