name: Boudoir Stories
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9604611080139875
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfcfcf'
    - '#f6f6f6'
    - '#000000'
    - '#868686'
    - '#515151'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
